<a href="https://colab.research.google.com/github/akashpambhar21/CE005_ML_AkashPambhar/blob/main/ML_Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [2]:
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [4]:
w = torch.randn(3, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[1.2335],
        [0.0894],
        [1.3316]], requires_grad=True)
tensor([-1.0852], requires_grad=True)


In [5]:
def model(x):
    return x @ w + b

In [6]:
preds = model(inputs)
print(preds)

tensor([[152.2122],
        [204.2567],
        [195.4469],
        [177.8494],
        [185.8234]], grad_fn=<AddBackward0>)


In [7]:
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [8]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [9]:
loss = mse(preds, targets)
print(loss)

tensor(12288.3760, grad_fn=<DivBackward0>)


In [10]:
loss.backward()

In [11]:
print(w)
print(w.grad)

tensor([[1.2335],
        [0.0894],
        [1.3316]], requires_grad=True)
tensor([[18600.8730],
        [16875.7051],
        [11209.4160]])


In [12]:
preds = model(inputs)
print(preds)

tensor([[152.2122],
        [204.2567],
        [195.4469],
        [177.8494],
        [185.8234]], grad_fn=<AddBackward0>)


In [13]:
loss = mse(preds, targets)
print(loss)

tensor(12288.3760, grad_fn=<DivBackward0>)


In [14]:
loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)

tensor([[37201.7461],
        [33751.4102],
        [22418.8320]])
tensor([427.6709])


In [15]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [17]:
print(w)
print(b)

tensor([[ 0.8615],
        [-0.2481],
        [ 1.1074]], requires_grad=True)
tensor([-1.0894], requires_grad=True)


In [18]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2547.0520, grad_fn=<DivBackward0>)


In [19]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    print(loss);
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

tensor(2547.0520, grad_fn=<DivBackward0>)
tensor(2008.1266, grad_fn=<DivBackward0>)
tensor(1762.2906, grad_fn=<DivBackward0>)
tensor(1637.7834, grad_fn=<DivBackward0>)
tensor(1563.8386, grad_fn=<DivBackward0>)
tensor(1511.2906, grad_fn=<DivBackward0>)
tensor(1468.1111, grad_fn=<DivBackward0>)
tensor(1429.3323, grad_fn=<DivBackward0>)
tensor(1392.8932, grad_fn=<DivBackward0>)
tensor(1357.9325, grad_fn=<DivBackward0>)
tensor(1324.0815, grad_fn=<DivBackward0>)
tensor(1291.1765, grad_fn=<DivBackward0>)
tensor(1259.1376, grad_fn=<DivBackward0>)
tensor(1227.9196, grad_fn=<DivBackward0>)
tensor(1197.4924, grad_fn=<DivBackward0>)
tensor(1167.8323, grad_fn=<DivBackward0>)
tensor(1138.9182, grad_fn=<DivBackward0>)
tensor(1110.7305, grad_fn=<DivBackward0>)
tensor(1083.2512, grad_fn=<DivBackward0>)
tensor(1056.4620, grad_fn=<DivBackward0>)
tensor(1030.3455, grad_fn=<DivBackward0>)
tensor(1004.8849, grad_fn=<DivBackward0>)
tensor(980.0635, grad_fn=<DivBackward0>)
tensor(955.8652, grad_fn=<DivBackwa

In [20]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(147.7858, grad_fn=<DivBackward0>)


In [21]:
preds

tensor([[ 60.2321],
        [ 87.8925],
        [100.8281],
        [ 40.3387],
        [100.3572]], grad_fn=<AddBackward0>)

In [22]:
targets


tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])